# Generated by Django 4.2.5 on 2023-09-27 14:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 9, 27, 14, 9, 11, 688206, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.UUIDField(default=uuid.UUID('59138d98-a913-4978-8a1f-477b328e396e')),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cf2b688-f97b-407d-a324-dcee6a4a2a85'), primary_key=True, serialize=False),
        ),
    ]
